"""
Tests for the registry/vault reconciliation.

The harvest writes into the edge store that feeds every generation prompt's
LINEAGE layer, so a wrong edge is not cosmetic — it becomes context the model is
told is true. The properties that matter:

  * full-name matching only, never a fragment. 'Aetherium' inside 'Aetherium
    Shards' must not link every artifact to every other one;
  * hubs are not relationships. An Index that lists all 70 pages would otherwise
    connect everything to everything;
  * relationships the registry already holds are never duplicated;
  * canon page text is read and never written.
"""

import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from layer5_dna_substrate.link_harvest import (  # noqa: E402
    apply_edges, candidate_entities, entity_index, harvest_edges, load_pages,
    register_entities, render_worklist, unlinked_character_pairs,
)
from layer5_dna_substrate.registry import DNARegistry  # noqa: E402


def page(vault, folder, stem, body, status="draft"):
    path = os.path.join(vault, folder) if folder else vault
    os.makedirs(path, exist_ok=True)
    with open(os.path.join(path, stem + ".md"), "w", encoding="utf-8") as fh:
        fh.write(f"---\nstatus: {status}\n---\n\n{body}")


@pytest.fixture
def world(tmp_path):
    vault = str(tmp_path)
    reg = DNARegistry()
    ids = {
        "Emberhold": reg.register_element("settlement", "S{}", "b",
                                          name="Emberhold", tags=["canonized"]),
        "Archivist Kaelen": reg.register_element("npc", "N{}", "b",
                                                 name="Archivist Kaelen"),
        "Chief Scrivener Lyra": reg.register_element("npc", "N{}", "b",
                                                     name="Chief Scrivener Lyra"),
        "Aetherium Shards": reg.register_element("item", "I{}", "b",
                                                 name="Aetherium Shards"),
        "Aetherium": reg.register_element("lore", "L{}", "b", name="Aetherium"),
    }
    page(vault, "Atlas", "Emberhold",
         "The city trades in [[Aetherium Shards]]. Archivist Kaelen walks here.",
         status="canon")
    page(vault, "Characters", "Archivist Kaelen",
         "He keeps the stacks. He fears Chief Scrivener Lyra.")
    page(vault, "Characters", "Chief Scrivener Lyra", "She rules the Guild.")
    page(vault, "Artifacts", "Aetherium Shards", "Shards of raw power.")
    page(vault, "Lore", "Aetherium", "A substance nobody understands.")
    return vault, reg, ids


def test_hub_and_template_pages_are_ignored(world):
    vault, reg, _ = world
    page(vault, "", "Index", "[[Emberhold]] [[Archivist Kaelen]]")
    page(vault, "Templates", "Character", "[[Emberhold]]")
    page(vault, "Atlas", "Atlas", "[[Emberhold]]")
    pages = load_pages(vault)

    assert "Index" not in pages
    assert "Character" not in pages
    assert "Atlas" not in pages, "a folder note is navigation, not content"
    assert "Emberhold" in pages


def test_the_deriver_does_not_read_its_own_output(world):
    """
    The worklist names every character, so if it were treated as content each
    pair would cite it as a page they share -- evidence generated by the run
    that reports it.
    """
    vault, reg, _ = world
    page(vault, "Drafts", "Link Gaps",
         "| [[Archivist Kaelen]] | [[Chief Scrivener Lyra]] |\n"
         "Archivist Kaelen and Chief Scrivener Lyra")
    with open(os.path.join(vault, "Drafts", "Link Gaps.md"),
              "w", encoding="utf-8") as fh:
        fh.write("---\ntype: meta\nstatus: draft\n---\n\n"
                 "Archivist Kaelen and Chief Scrivener Lyra")
    pages = load_pages(vault)

    assert "Link Gaps" not in pages
    assert all("Link Gaps" not in r["shared_pages"]
               for r in unlinked_character_pairs(reg, pages))


def test_wikilink_the_registry_lacks_is_harvested(world):
    vault, reg, ids = world
    rows = harvest_edges(reg, load_pages(vault))
    hit = [r for r in rows
           if r["source"] == "Emberhold" and r["target"] == "Aetherium Shards"]

    assert len(hit) == 1
    assert hit[0]["kind"] == "wikilink"
    assert hit[0]["label"] == "mentions_Aetherium Shards"


def test_bare_prose_mention_is_harvested_as_prose(world):
    vault, reg, _ = world
    rows = harvest_edges(reg, load_pages(vault))
    hit = [r for r in rows
           if r["source"] == "Archivist Kaelen"
           and r["target"] == "Chief Scrivener Lyra"]

    assert len(hit) == 1
    assert hit[0]["kind"] == "prose", "no wikilink exists for this one"


def test_a_name_that_is_a_prefix_of_another_does_not_cross_link(world):
    """'Aetherium' must not match inside 'Aetherium Shards'."""
    vault, reg, _ = world
    rows = harvest_edges(reg, load_pages(vault))
    bad = [r for r in rows
           if {r["source"], r["target"]} == {"Aetherium Shards", "Aetherium"}]

    assert bad == [], "substring matching would link every artifact to the lore"


def test_relationships_already_in_the_registry_are_not_repeated(world):
    vault, reg, ids = world
    reg.link_elements(ids["Emberhold"], ids["Aetherium Shards"],
                      "peer", "mentions_Aetherium Shards")
    rows = harvest_edges(reg, load_pages(vault))

    assert not [r for r in rows if r["target"] == "Aetherium Shards"
                and r["source"] == "Emberhold"]


def test_apply_writes_edges_and_is_idempotent(world):
    vault, reg, _ = world
    pages = load_pages(vault)
    added = apply_edges(reg, harvest_edges(reg, pages))

    assert added > 0
    assert harvest_edges(reg, pages) == [], "a second pass must find nothing"


def test_apply_can_be_restricted_to_wikilinks(world):
    vault, reg, _ = world
    rows = harvest_edges(reg, load_pages(vault))
    added = apply_edges(reg, rows, kinds={"wikilink"})

    assert added == len([r for r in rows if r["kind"] == "wikilink"])


def test_characters_sharing_a_page_without_a_link_are_listed(world):
    vault, reg, _ = world
    page(vault, "Factions", "The Guild",
         "Archivist Kaelen and Chief Scrivener Lyra both serve here.")
    pairs = unlinked_character_pairs(reg, load_pages(vault))

    assert len(pairs) == 1
    assert {pairs[0]["a"], pairs[0]["b"]} == {"Archivist Kaelen",
                                              "Chief Scrivener Lyra"}
    assert "The Guild" in pairs[0]["shared_pages"]


def test_characters_with_an_explicit_link_are_not_listed(world):
    vault, reg, _ = world
    page(vault, "Characters", "Archivist Kaelen",
         "He fears [[Chief Scrivener Lyra]].")
    page(vault, "Factions", "The Guild",
         "Archivist Kaelen and Chief Scrivener Lyra both serve here.")

    assert unlinked_character_pairs(reg, load_pages(vault)) == []


def test_emphasised_names_canon_never_registered_are_surfaced(world):
    vault, reg, _ = world
    page(vault, "Factions", "The Guild",
         'Initiation demands the **Vow of the Blank Page**, and the '
         '"Law of Utility" governs all trade.', status="canon")
    found = {c["name"] for c in candidate_entities(reg, load_pages(vault))}

    assert "Vow of the Blank Page" in found
    assert "Law of Utility" in found


def test_section_headers_are_not_mistaken_for_entities(world):
    vault, reg, _ = world
    page(vault, "Factions", "The Guild",
         "### Secrets & Shadows\n\n**Adventure Hooks**\n\n**Behavioral Model**",
         status="canon")
    found = {c["name"] for c in candidate_entities(reg, load_pages(vault))}

    assert "Adventure Hooks" not in found
    assert "Behavioral Model" not in found


def test_a_thing_that_already_has_a_page_is_not_a_candidate(world):
    vault, reg, _ = world
    page(vault, "Factions", "The Guild", "**Aetherium Shards** matter.",
         status="canon")

    assert "Aetherium Shards" not in {
        c["name"] for c in candidate_entities(reg, load_pages(vault))}


def test_registered_entities_look_like_pipeline_stubs(world):
    """The stub index and context assembler must not tell them apart."""
    vault, reg, ids = world
    rows = [{"name": "Law of Utility", "sources": ["Emberhold"],
             "canon_sources": ["Emberhold"]}]
    created = register_entities(reg, rows, "lore", load_pages(vault))

    assert len(created) == 1
    record = reg.get_element(created[0])
    assert record["type"] == "lore"
    assert "stub" in record["tags"]
    assert f"from_{ids['Emberhold']}" in record["tags"]
    assert record["stub_metadata"]["name"] == "Law of Utility"
    assert record["stub_metadata"]["source_id"] == ids["Emberhold"]
    # and it is linked back to the page that named it
    assert created[0] in [i["id"] for i in reg._edges[ids["Emberhold"]]["peer"]]


def test_a_stub_with_no_source_page_still_reads_sensibly(world):
    """Some things are named only in a derived page, which is not an entity."""
    vault, reg, _ = world
    created = register_entities(
        reg, [{"name": "The Tally", "sources": [], "canon_sources": []}],
        "lore", load_pages(vault))

    assert "None" not in reg.get_element(created[0])["gist"]
    assert reg.get_element(created[0])["stub_metadata"]["source_id"] is None


def test_registering_an_existing_name_is_a_no_op(world):
    vault, reg, _ = world
    rows = [{"name": "Aetherium Shards", "sources": [], "canon_sources": []}]

    assert register_entities(reg, rows, "lore", load_pages(vault)) == []


def test_harvest_never_writes_to_the_vault(world):
    vault, reg, _ = world
    before = {p: open(os.path.join(r, f), encoding="utf-8").read()
              for r, _, fs in os.walk(vault) for f in fs
              for p in [os.path.join(r, f)]}
    pages = load_pages(vault)
    harvest_edges(reg, pages)
    candidate_entities(reg, pages)
    unlinked_character_pairs(reg, pages)
    after = {p: open(p, encoding="utf-8").read() for p in before}

    assert before == after, "canon is read-only to this deriver"


def test_worklist_renders_without_a_dataview_dependency(world):
    vault, reg, _ = world
    pages = load_pages(vault)
    text = render_worklist(unlinked_character_pairs(reg, pages),
                           candidate_entities(reg, pages),
                           harvest_edges(reg, pages))

    assert text.startswith("---\n")
    assert "# Link Gaps" in text
    assert "dataview" not in text
