import os
import json
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser

class LoreExtractor:
    """
    Parses massive blocks of raw generated narrative history and extracts 
    structural data points (the "Crunch") into a strict JSON schema that 
    the WorldStateKeeper can ingest.
    """
    def __init__(self):
        api_key = os.getenv("OLLAMA_API_KEY", "dummy_key")
        base_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1")
        
        self.llm = ChatOpenAI(
            model="qwen3.5:397b-cloud",
            temperature=0.0, # Zero temp for exact data extraction
            api_key=api_key,
            base_url=base_url
        )
        
        # Define the expected JSON schema implicitly in the prompt, or use Pydantic
        # For this MVP, we will rely on a strict prompt and JSON parsing.
        template = """
You are a precise data extraction algorithm. 
Review the following text generated by multiple historians detailing the history of a fantasy world.

HISTORY LOG:
{history_log}

Extract the key structural elements from this text and output ONLY valid JSON using the exact schema provided below. Do not include markdown formatting like ```json or any conversational text.

EXPECTED JSON SCHEMA:
{{
  "world_name": "string (infer a name if not directly stated, else 'The Realm')",
  "active_factions": [{{"id": "uuid4 string format", "name": "string", "disposition": "integer 1-20 (guess based on lore)"}}],
  "ruined_factions": [{{"name": "string", "cause_of_ruin": "string"}}],
  "significant_locations": [{{"name": "string", "status": "active|ruined", "controlling_faction_name": "string or null"}}],
  "historical_eras": [{{"era_name": "string string (invent a title based on the events)", "defining_event": "string summary string"}}],
  "active_crises": [{{"description": "string", "threat_level": "integer 1-20"}}],
  "laws_of_magic": "string (summarize any notable magical shifts)",
  "timeline_year": "integer (guess an establishing year, e.g., 1000)"
}}
"""
        self.prompt = PromptTemplate(
            template=template,
            input_variables=["history_log"]
        )
        # Using JsonOutputParser to enforce JSON format handling from the LLM
        self.parser = JsonOutputParser()
        self.chain = self.prompt | self.llm | self.parser

    async def extract_data(self, history_log: str) -> dict:
        """Parses the history log and returns a structured dictionary."""
        print("\n[LoreExtractor] Parsing consensus history into structural JSON...")
        try:
            # We use ainvoke and rely on the JsonOutputParser to handle the raw string
            extracted_json = await self.chain.ainvoke({"history_log": history_log})
            return extracted_json
        except Exception as e:
            print(f"[LoreExtractor] Error extracting JSON: {e}")
            # Fallback safe schema structure
            return {
                "world_name": "Unknown Realm",
                "active_factions": [],
                "ruined_factions": [],
                "significant_locations": [],
                "historical_eras": [],
                "active_crises": [],
                "laws_of_magic": "Unknown",
                "timeline_year": 0
            }
