import os
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from typing import List, Dict

class HistoryConsensusEngine:
    """
    A 'Microscope'-style consensus engine where 4 distinct AI personas take turns
    expanding on a core World DNA seed to generate deep historical periods and events.
    """
    def __init__(self, safety_governor=None):
        self.safety_governor = safety_governor
        
        from layer1_core.model_router import model_router
        self.llm = model_router.get_llm("history_consensus", temperature=0.7)
        self.parser = StrOutputParser()
        
        # Define the personas
        self.personas = {
            "The Scholar": "You are The Scholar. You focus on politics, borders, major treaties, and empirical facts.",
            "The Myth-Maker": "You are The Myth-Maker. You focus on legends, religious shifts, grand heroes, and dramatic tragedies.",
            "The Pragmatist": "You are The Pragmatist. You focus on economics, famine, disease, trade routes, and the struggles of the common folk.",
            "The Arcane Record-Keeper": "You are The Arcane Record-Keeper. You focus on magical anomalies, the creation of artifacts, and shifts in the cosmic balance."
        }
        
        self.prompt_template = PromptTemplate(
            template="""
{persona_prompt}
You are playing a collaborative world-building game.
Here is the raw "World DNA" decoded profile that serves as the foundation of reality:
{world_profile}

Here is the history generated by the other historians so far:
{current_history}

Your Task: Add ONE new significant Historical Era or Major Event to the timeline. 
It must logically follow the previous events, but must reflect YOUR persona's specific interests.
Write a 1-2 paragraph description of what happened. Do not contradict established facts.
""",
            input_variables=["persona_prompt", "world_profile", "current_history"]
        )
        self.chain = self.prompt_template | self.llm | self.parser

    async def generate_history(self, decoded_world_profile: str, rounds: int = 1, active_player_ids: List[str] = None) -> str:
        """
        Runs the consensus loop. Each persona takes a turn adding to the history log.
        Outputs are filtered through the Safety Governor if provided.
        """
        print(f"\n[ConsensusEngine] Initiating Microscope loop for {rounds} round(s)...")
        history_log = "Dawn of the World: The fundamental forces coalesced, establishing the rules of reality.\n"
        
        for round_num in range(rounds):
            print(f"\n--- Historical Epoch {round_num + 1} ---")
            for persona_name, persona_prompt in self.personas.items():
                print(f"[{persona_name}] is writing...")
                
                try:
                    contribution = await self.chain.ainvoke({
                        "persona_prompt": persona_prompt,
                        "world_profile": decoded_world_profile,
                        "current_history": history_log
                    })
                    
                    # Safety check
                    if self.safety_governor:
                        safety_check = await self.safety_governor.filter_content(contribution, active_player_ids)
                        if safety_check["status"] == "invalid":
                            print(f"[ConsensusEngine] {persona_name}'s entry struck from records (Safety Violation).")
                            contribution = f"[{persona_name}'s dark records were sealed by the Inquisition and lost to time.]"
                    
                    history_log += f"\n\n### Recorded by {persona_name}:\n{contribution.strip()}"
                    
                except Exception as e:
                    print(f"[ConsensusEngine] Error during {persona_name}'s turn: {e}")
                    
        return history_log
